### ISSUE TITLE
Is this still used?

### ISSUE THREAD

**Issue by OmgImAlexis** [yagop/lunabot#1]
Hi I'm looking for a org name on GitHub for my discord bot Luna and wanted to use LunaBot but I see it's currently taken.
Is there any chance you'd be willing to allow me to take the name over?

**Comment by OmgImAlexis** [comment]
PING: @yagop

**Comment by yagop** [comment]
This project cant be used so I can free the name.
Are you sure you need an organization?

**Comment by OmgImAlexis** [comment]
Yes I plan on adding about 20 devs in my support group to help with the bot and it’ll be a lot easier with an org. 

Thank you so much for this.
